version: '3.8'
services:
  tuto-postgresql:
    image: postgres:14.5
    # volumes:
    #   - ~/volumes/tuto/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=tuto
      - POSTGRES_PASSWORD=tuto
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
