#server port
server:
  port: 8886

#application name
spring:
  application:
    name: TUTO-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/tuto
    username: tuto
    password: tuto
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #pour la recuperation de sa config
  cloud:
    config:
      uri: http://localhost:8888
#it is a eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost